name: fsstp
description: FSSTP is a Flutter plugin for SSTP/SoftEther VPN connections. It provides a convenient way to manage SSTP/SoftEther VPN connections, monitor connection status, and configure various settings.
version: 1.0.0
homepage: https://github.com/devstroop/fsstp

platforms:
  android:
  ios:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.4.0

flutter:
  plugin:
    platforms:
      android:
        package: com.devstroop.fsstp
        pluginClass: SstpFlutterPlugin
      ios:
        pluginClass: SstpFlutterPlugin

